export const MARGIN = {
  TOP_0: 'mt-0',
  TOP_1: 'mt-1',
  TOP_2: 'mt-2',
  TOP_3: 'mt-3',
  TOP_4: 'mt-4',
  TOP_5: 'mt-5',

  RIGHT_0: 'mr-0',
  RIGHT_1: 'mr-1',
  RIGHT_2: 'mr-2',
  RIGHT_3: 'mr-3',
  RIGHT_4: 'mr-4',
  RIGHT_5: 'mr-5',

  BOTTOM_0: 'mb-0',
  BOTTOM_1: 'mb-1',
  BOTTOM_2: 'mb-2',
  BOTTOM_3: 'mb-3',
  BOTTOM_4: 'mb-4',
  BOTTOM_5: 'mb-5',

  LEFT_0: 'ml-0',
  LEFT_1: 'ml-1',
  LEFT_2: 'ml-2',
  LEFT_3: 'ml-3',
  LEFT_4: 'ml-4',
  LEFT_5: 'ml-5',

  X_0: 'mx-0',
  X_1: 'mx-1',
  X_2: 'mx-2',
  X_3: 'mx-3',
  X_4: 'mx-4',
  X_5: 'mx-5',
  X_AUTO: 'mx-auto',

  Y_0: 'my-0',
  Y_1: 'my-1',
  Y_2: 'my-2',
  Y_3: 'my-3',
  Y_4: 'my-4',
  Y_5: 'my-5',

  SM_TOP_0: 'mt-sm-0',
  SM_TOP_1: 'mt-sm-1',
  SM_TOP_2: 'mt-sm-2',
  SM_TOP_3: 'mt-sm-3',
  SM_TOP_4: 'mt-sm-4',
  SM_TOP_5: 'mt-sm-5',

  SM_RIGHT_0: 'mr-sm-0',
  SM_RIGHT_1: 'mr-sm-1',
  SM_RIGHT_2: 'mr-sm-2',
  SM_RIGHT_3: 'mr-sm-3',
  SM_RIGHT_4: 'mr-sm-4',
  SM_RIGHT_5: 'mr-sm-5',

  SM_BOTTOM_0: 'mb-sm-0',
  SM_BOTTOM_1: 'mb-sm-1',
  SM_BOTTOM_2: 'mb-sm-2',
  SM_BOTTOM_3: 'mb-sm-3',
  SM_BOTTOM_4: 'mb-sm-4',
  SM_BOTTOM_5: 'mb-sm-5',

  SM_LEFT_0: 'ml-sm-0',
  SM_LEFT_1: 'ml-sm-1',
  SM_LEFT_2: 'ml-sm-2',
  SM_LEFT_3: 'ml-sm-3',
  SM_LEFT_4: 'ml-sm-4',
  SM_LEFT_5: 'ml-sm-5',

  SM_X_0: 'mx-sm-0',
  SM_X_1: 'mx-sm-1',
  SM_X_2: 'mx-sm-2',
  SM_X_3: 'mx-sm-3',
  SM_X_4: 'mx-sm-4',
  SM_X_5: 'mx-sm-5',

  SM_Y_0: 'my-sm-0',
  SM_Y_1: 'my-sm-1',
  SM_Y_2: 'my-sm-2',
  SM_Y_3: 'my-sm-3',
  SM_Y_4: 'my-sm-4',
  SM_Y_5: 'my-sm-5',

  MD_TOP_0: 'mt-md-0',
  MD_TOP_1: 'mt-md-1',
  MD_TOP_2: 'mt-md-2',
  MD_TOP_3: 'mt-md-3',
  MD_TOP_4: 'mt-md-4',
  MD_TOP_5: 'mt-md-5',

  MD_RIGHT_0: 'mr-md-0',
  MD_RIGHT_1: 'mr-md-1',
  MD_RIGHT_2: 'mr-md-2',
  MD_RIGHT_3: 'mr-md-3',
  MD_RIGHT_4: 'mr-md-4',
  MD_RIGHT_5: 'mr-md-5',

  MD_BOTTOM_0: 'mb-md-0',
  MD_BOTTOM_1: 'mb-md-1',
  MD_BOTTOM_2: 'mb-md-2',
  MD_BOTTOM_3: 'mb-md-3',
  MD_BOTTOM_4: 'mb-md-4',
  MD_BOTTOM_5: 'mb-md-5',

  MD_LEFT_0: 'ml-md-0',
  MD_LEFT_1: 'ml-md-1',
  MD_LEFT_2: 'ml-md-2',
  MD_LEFT_3: 'ml-md-3',
  MD_LEFT_4: 'ml-md-4',
  MD_LEFT_5: 'ml-md-5',

  MD_X_0: 'mx-md-0',
  MD_X_1: 'mx-md-1',
  MD_X_2: 'mx-md-2',
  MD_X_3: 'mx-md-3',
  MD_X_4: 'mx-md-4',
  MD_X_5: 'mx-md-5',

  MD_Y_0: 'my-md-0',
  MD_Y_1: 'my-md-1',
  MD_Y_2: 'my-md-2',
  MD_Y_3: 'my-md-3',
  MD_Y_4: 'my-md-4',
  MD_Y_5: 'my-md-5',

  LG_TOP_0: 'mt-lg-0',
  LG_TOP_1: 'mt-lg-1',
  LG_TOP_2: 'mt-lg-2',
  LG_TOP_3: 'mt-lg-3',
  LG_TOP_4: 'mt-lg-4',
  LG_TOP_5: 'mt-lg-5',

  LG_RIGHT_0: 'mr-lg-0',
  LG_RIGHT_1: 'mr-lg-1',
  LG_RIGHT_2: 'mr-lg-2',
  LG_RIGHT_3: 'mr-lg-3',
  LG_RIGHT_4: 'mr-lg-4',
  LG_RIGHT_5: 'mr-lg-5',

  LG_BOTTOM_0: 'mb-lg-0',
  LG_BOTTOM_1: 'mb-lg-1',
  LG_BOTTOM_2: 'mb-lg-2',
  LG_BOTTOM_3: 'mb-lg-3',
  LG_BOTTOM_4: 'mb-lg-4',
  LG_BOTTOM_5: 'mb-lg-5',

  LG_LEFT_0: 'ml-lg-0',
  LG_LEFT_1: 'ml-lg-1',
  LG_LEFT_2: 'ml-lg-2',
  LG_LEFT_3: 'ml-lg-3',
  LG_LEFT_4: 'ml-lg-4',
  LG_LEFT_5: 'ml-lg-5',

  LG_X_0: 'mx-lg-0',
  LG_X_1: 'mx-lg-1',
  LG_X_2: 'mx-lg-2',
  LG_X_3: 'mx-lg-3',
  LG_X_4: 'mx-lg-4',
  LG_X_5: 'mx-lg-5',

  LG_Y_0: 'my-lg-0',
  LG_Y_1: 'my-lg-1',
  LG_Y_2: 'my-lg-2',
  LG_Y_3: 'my-lg-3',
  LG_Y_4: 'my-lg-4',
  LG_Y_5: 'my-lg-5',

  XL_TOP_0: 'mt-xl-0',
  XL_TOP_1: 'mt-xl-1',
  XL_TOP_2: 'mt-xl-2',
  XL_TOP_3: 'mt-xl-3',
  XL_TOP_4: 'mt-xl-4',
  XL_TOP_5: 'mt-xl-5',

  XL_RIGHT_0: 'mr-xl-0',
  XL_RIGHT_1: 'mr-xl-1',
  XL_RIGHT_2: 'mr-xl-2',
  XL_RIGHT_3: 'mr-xl-3',
  XL_RIGHT_4: 'mr-xl-4',
  XL_RIGHT_5: 'mr-xl-5',

  XL_BOTTOM_0: 'mb-xl-0',
  XL_BOTTOM_1: 'mb-xl-1',
  XL_BOTTOM_2: 'mb-xl-2',
  XL_BOTTOM_3: 'mb-xl-3',
  XL_BOTTOM_4: 'mb-xl-4',
  XL_BOTTOM_5: 'mb-xl-5',

  XL_LEFT_0: 'ml-xl-0',
  XL_LEFT_1: 'ml-xl-1',
  XL_LEFT_2: 'ml-xl-2',
  XL_LEFT_3: 'ml-xl-3',
  XL_LEFT_4: 'ml-xl-4',
  XL_LEFT_5: 'ml-xl-5',

  XL_X_0: 'mx-xl-0',
  XL_X_1: 'mx-xl-1',
  XL_X_2: 'mx-xl-2',
  XL_X_3: 'mx-xl-3',
  XL_X_4: 'mx-xl-4',
  XL_X_5: 'mx-xl-5',

  XL_Y_0: 'my-xl-0',
  XL_Y_1: 'my-xl-1',
  XL_Y_2: 'my-xl-2',
  XL_Y_3: 'my-xl-3',
  XL_Y_4: 'my-xl-4',
  XL_Y_5: 'my-xl-5',
};
