#!/usr/bin/env node
require('babel-register')();

const server = require('./server').default;

server.set('port', process.env.PORT || 8080);

server.listen(server.get('port'), () => {
  console.log(`Express server listening on port ${server.get('port')}`);
});
